using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Soundbox.Speech.Recognition
{
    /// <summary>
    /// Base class for events generated by <see cref="ISpeechRecognitionService"/>
    /// </summary>
    public class SpeechRecognitionBaseEvent : EventArgs
    {
        /// <summary>
        /// Timestamp at which the event had been generated.
        /// </summary>
        [JsonIgnore]
        public long TimestampMillis { get; set; } = Environment.TickCount;
    }
}
