using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Soundbox.Speech.Recognition
{
    /// <summary>
    /// Base class for events generated by <see cref="ISpeechRecognitionService"/>
    /// </summary>
    public class SpeechRecognitionBaseEvent : EventArgs
    {
        public ISpeechRecognitionService SpeechRecognizer { get; set; }
    }
}
